-   id: autoformat-commit-msg
    name: Git message autoformat
    description: Automatically reformat your Git commit messages
    entry: autoformat_commit.py
    language: script
    stages: [prepare-commit-msg]
    always_run: true
